default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta build to hockeyapp"
  lane :upload_app_center do
    # ref: https://docs.fastlane.tools/actions/hockey/
    # hockey(
    #   api_token: ENV["HOCKEY_APP_API_KEY"],
    #   apk: ENV["APK_PATH"],
    #   # public_identifier: ENV["public_identifier"],
    #   # bundle_short_version: ENV["bundle_short_version"],
    #   # bundle_version: ENV["bundle_version"],
    #   notes: "Changelog",
    #   strategy: "replace" # Replace existing builds with the same build number
    #   # create_update: true,
    # )

    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "Lewis",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "MyWell-Dev",
      file: ENV["APK_PATH"],
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )

  end

 


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
