default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta build to appcenter"
  lane :upload_app_center do
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "lewis-vesselstech.com",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: ENV["APPCENTER_APP_NAME"],
      file: ENV["APK_PATH"],
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
