
/**
 * Step 1:
 * Add the new action types for the action request and response here.
 */
export enum ActionType {
  ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST',
  ADD_FAVOURITE_RESPONSE = 'ADD_FAVOURITE_RESPONSE',

  ADD_RECENT_REQUEST = 'ADD_RECENT_REQUEST',
  ADD_RECENT_RESPONSE = 'ADD_RECENT_RESPONSE',

  CONNECT_TO_EXTERNAL_SERVICE_REQUEST = 'CONNECT_TO_EXTERNAL_SERVICE_REQUEST',
  CONNECT_TO_EXTERNAL_SERVICE_RESPONSE = 'CONNECT_TO_EXTERNAL_SERVICE_RESPONSE',

  DISCONNECT_FROM_EXTERNAL_SERVICE_REQUEST = 'DISCONNECT_FROM_EXTERNAL_SERVICE_REQUEST',
  DISCONNECT_FROM_EXTERNAL_SERVICE_RESPONSE = 'DISCONNECT_FROM_EXTERNAL_SERVICE_RESPONSE',

  GET_EXTERNAL_LOGIN_DETAILS_REQUEST = 'GET_EXTERNAL_LOGIN_DETAILS_REQUEST',
  GET_EXTERNAL_LOGIN_DETAILS_RESPONSE = 'GET_EXTERNAL_LOGIN_DETAILS_RESPONSE',

  GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST',
  GET_LOCATION_RESPONSE = 'GET_LOCATION_RESPONSE',

  GET_READINGS_REQUEST = 'GET_READINGS_REQUEST',
  GET_READINGS_RESPONSE = 'GET_READINGS_RESPONSE',

  GET_RESOURCES_REQUEST = 'GET_RESOURCES_REQUEST',
  GET_RESOURCES_RESPONSE = 'GET_RESOURCES_RESPONSE',

  GET_USER_REQUEST = 'GET_USER_REQUEST',
  GET_USER_RESPONSE = 'GET_USER_RESPONSE',

  REMOVE_FAVOURITE_REQUEST = 'REMOVE_FAVOURITE_REQUEST',
  REMOVE_FAVOURITE_RESPONSE = 'REMOVE_FAVOURITE_RESPONSE',
  
  SAVE_READING_REQUEST = 'SAVE_READING_REQUEST',
  SAVE_READING_RESPONSE = 'SAVE_READING_RESPONSE',

  SAVE_RESOURCE_REQUEST = 'SAVE_RESOURCE_REQUEST',
  SAVE_RESOURCE_RESPONSE = 'SAVE_RESOURCE_RESPONSE',

  SILENT_LOGIN_REQUEST = 'SILENT_LOGIN_REQUEST',
  SILENT_LOGIN_RESPONSE = 'SILENT_LOGIN_RESPONSE',

  TOGGLE_CONNECTION = 'TOGGLE_CONNECTION',

  //TODO: add recent searches action
}