
export should_send_emails=false
export service_account_key_filename=.serviceAccountKey.development.json
export backup_service_account_key_filename=.backupServiceAccountKey.development.js
export backup_bucket_name=our-water-dev-backup
export PROJECT_ID=our-water-dev